### ISSUE TITLE
ValueError: Namespace WebKit not available

### ISSUE THREAD

**Issue by ph1losof** [epsylon/paranoia-browser#1]
Traceback (most recent call last):
  File "./pArAnoIA.py", line 10, in <module>
    from core.main import Browser
  File "/root/paranoia-browser/core/main.py", line 14, in <module>
    gi.require_version('WebKit', '3.0')
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit not available

**Comment by epsylon** [comment]
Hi @philosofonusus
Try to install this library:
gir1.2-webkit-3.0 - Web content engine library for GTK+ - GObject introspection data
ex:
**sudo apt-get install gir1.2-webkit-3.0**

**Comment by ph1losof** [comment]
sudo apt-get install gir1.2-webkit-3.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package gir1.2-webkit-3.0
E: Couldn't find any package by glob 'gir1.2-webkit-3.0'
E: Couldn't find any package by regex 'gir1.2-webkit-3.0'

**Comment by epsylon** [comment]
You need the web content engine library for GTK+. Try this other:
- gir1.2-webkit2-4.0 - Web content engine library for GTK+ - GObject introspection data
**sudo apt-get install gir1.2-webkit2-4.0**

**Comment by epsylon** [comment]
pArAnoIA-Browser has been ported to Python3.x: https://github.com/epsylon/paranoia-browser/commit/1f8c487c74275d5218ee7d0f03ec5d44ddd734ee
