### ISSUE TITLE
Error when trying to run

### ISSUE THREAD

**Issue by pxwndev** [epsylon/paranoia-browser#2]
root@prevail:~/pArAnoIA-Browser# python2 pArAnoIA.py
Traceback (most recent call last):
  File "pArAnoIA.py", line 10, in <module>
    from core.main import Browser
  File "/root/pArAnoIA-Browser/core/main.py", line 10, in <module>
    import os, sys, gi, re, random, socket, requests, time, pygeoip, urlparse, urllib2
ImportError: No module named gi
 :/ im new to this.

**Comment by pxwndev** [comment]
??

**Comment by epsylon** [comment]
Hi @pxwndev
Try to install this library:
gir1.2-webkit2-4.0 - Web content engine library for GTK+ - GObject introspection data
sudo apt-get install gir1.2-webkit2-4.0
