### ISSUE TITLE
status of this project, python3 migration

### ISSUE THREAD

**Issue by chaosmonk1** [epsylon/paranoia-browser#4]
This project looks promising, but there is no evidence of activity since the initial commit six months ago.  Python 2 reaches end-of-life in a few weeks and will no longer receive security updates, so it seems like paranoia-browser needs to migrate to Python 3.  I am willing to help with Python 3 migration, but before I start putting time into it would like to know whether you are planning to continue to develop this browser.

Thanks

**Comment by chaosmonk1** [comment]
I would also be willing to take a stab at migrating from WebKit to WebKit2 in order to fix https://github.com/epsylon/paranoia-browser/issues/3, again, if you can confirm that this project is going to continue to be developed.

**Comment by epsylon** [comment]
pArAnoIA-Browser has been ported to Python3.x: https://github.com/epsylon/paranoia-browser/commit/1f8c487c74275d5218ee7d0f03ec5d44ddd734ee
